tx set -r safeslinger.exchxml -l af res/values-af/strings.xml
tx set -r safeslinger.exchxml -l sq res/values-sq/strings.xml
tx set -r safeslinger.exchxml -l ar res/values-ar/strings.xml
tx set -r safeslinger.exchxml -l hy res/values-hy/strings.xml
tx set -r safeslinger.exchxml -l az res/values-az/strings.xml
tx set -r safeslinger.exchxml -l eu res/values-eu/strings.xml
tx set -r safeslinger.exchxml -l be res/values-be/strings.xml
tx set -r safeslinger.exchxml -l bn res/values-bn/strings.xml
tx set -r safeslinger.exchxml -l bs res/values-bs/strings.xml
tx set -r safeslinger.exchxml -l bg res/values-bg/strings.xml
tx set -r safeslinger.exchxml -l ca res/values-ca/strings.xml
tx set -r safeslinger.exchxml -l ceb res/values-cb/strings.xml
tx set -r safeslinger.exchxml -l zh_CN res/values-zh-rCN/strings.xml
tx set -r safeslinger.exchxml -l zh_TW res/values-zh-rTW/strings.xml
tx set -r safeslinger.exchxml -l hr res/values-hr/strings.xml
tx set -r safeslinger.exchxml -l cs res/values-cs/strings.xml
tx set -r safeslinger.exchxml -l da res/values-da/strings.xml
tx set -r safeslinger.exchxml -l nl res/values-nl/strings.xml
tx set --source -r safeslinger.exchxml -l en res/values/strings.xml
tx set -r safeslinger.exchxml -l eo res/values-eo/strings.xml
tx set -r safeslinger.exchxml -l et res/values-et/strings.xml
tx set -r safeslinger.exchxml -l tl res/values-tl/strings.xml
tx set -r safeslinger.exchxml -l fi res/values-fi/strings.xml
tx set -r safeslinger.exchxml -l fr res/values-fr/strings.xml
tx set -r safeslinger.exchxml -l gl res/values-gl/strings.xml
tx set -r safeslinger.exchxml -l ka res/values-ka/strings.xml
tx set -r safeslinger.exchxml -l de res/values-de/strings.xml
tx set -r safeslinger.exchxml -l el res/values-el/strings.xml
tx set -r safeslinger.exchxml -l gu res/values-gu/strings.xml
tx set -r safeslinger.exchxml -l ht res/values-ht/strings.xml
tx set -r safeslinger.exchxml -l ha res/values-ha/strings.xml
tx set -r safeslinger.exchxml -l he res/values-iw/strings.xml
tx set -r safeslinger.exchxml -l hi res/values-hi/strings.xml
tx set -r safeslinger.exchxml -l hmn res/values-hm/strings.xml
tx set -r safeslinger.exchxml -l hu res/values-hu/strings.xml
tx set -r safeslinger.exchxml -l is res/values-is/strings.xml
tx set -r safeslinger.exchxml -l ig res/values-ig/strings.xml
tx set -r safeslinger.exchxml -l id res/values-in/strings.xml
tx set -r safeslinger.exchxml -l ga res/values-ga/strings.xml
tx set -r safeslinger.exchxml -l it res/values-it/strings.xml
tx set -r safeslinger.exchxml -l ja res/values-ja/strings.xml
tx set -r safeslinger.exchxml -l jv res/values-jv/strings.xml
tx set -r safeslinger.exchxml -l kn res/values-kn/strings.xml
tx set -r safeslinger.exchxml -l km res/values-km/strings.xml
tx set -r safeslinger.exchxml -l ko res/values-ko/strings.xml
tx set -r safeslinger.exchxml -l lo res/values-lo/strings.xml
tx set -r safeslinger.exchxml -l la res/values-la/strings.xml
tx set -r safeslinger.exchxml -l lv res/values-lv/strings.xml
tx set -r safeslinger.exchxml -l lt res/values-lt/strings.xml
tx set -r safeslinger.exchxml -l mk res/values-mk/strings.xml
tx set -r safeslinger.exchxml -l ms res/values-ms/strings.xml
tx set -r safeslinger.exchxml -l mt res/values-mt/strings.xml
tx set -r safeslinger.exchxml -l mi res/values-mi/strings.xml
tx set -r safeslinger.exchxml -l mr res/values-mr/strings.xml
tx set -r safeslinger.exchxml -l mn res/values-mn/strings.xml
tx set -r safeslinger.exchxml -l ne res/values-ne/strings.xml
tx set -r safeslinger.exchxml -l no res/values-no/strings.xml
tx set -r safeslinger.exchxml -l fa res/values-fa/strings.xml
tx set -r safeslinger.exchxml -l pl res/values-pl/strings.xml
tx set -r safeslinger.exchxml -l pt res/values-pt/strings.xml
tx set -r safeslinger.exchxml -l pa res/values-pa/strings.xml
tx set -r safeslinger.exchxml -l ro res/values-ro/strings.xml
tx set -r safeslinger.exchxml -l ru res/values-ru/strings.xml
tx set -r safeslinger.exchxml -l sr res/values-sr/strings.xml
tx set -r safeslinger.exchxml -l sk res/values-sk/strings.xml
tx set -r safeslinger.exchxml -l sl res/values-sl/strings.xml
tx set -r safeslinger.exchxml -l so res/values-so/strings.xml
tx set -r safeslinger.exchxml -l es res/values-es/strings.xml
tx set -r safeslinger.exchxml -l sw res/values-sw/strings.xml
tx set -r safeslinger.exchxml -l sv res/values-sv/strings.xml
tx set -r safeslinger.exchxml -l ta res/values-ta/strings.xml
tx set -r safeslinger.exchxml -l te res/values-te/strings.xml
tx set -r safeslinger.exchxml -l th res/values-th/strings.xml
tx set -r safeslinger.exchxml -l tr res/values-tr/strings.xml
tx set -r safeslinger.exchxml -l uk res/values-uk/strings.xml
tx set -r safeslinger.exchxml -l ur res/values-ur/strings.xml
tx set -r safeslinger.exchxml -l vi res/values-vi/strings.xml
tx set -r safeslinger.exchxml -l cy res/values-cy/strings.xml
tx set -r safeslinger.exchxml -l yi res/values-ji/strings.xml
tx set -r safeslinger.exchxml -l yo res/values-yo/strings.xml
tx set -r safeslinger.exchxml -l zu res/values-zu/strings.xml