tx set -r safeslinger.msgrxml -l af res/values-af/strings.xml
tx set -r safeslinger.msgrxml -l sq res/values-sq/strings.xml
tx set -r safeslinger.msgrxml -l ar res/values-ar/strings.xml
tx set -r safeslinger.msgrxml -l hy res/values-hy/strings.xml
tx set -r safeslinger.msgrxml -l az res/values-az/strings.xml
tx set -r safeslinger.msgrxml -l eu res/values-eu/strings.xml
tx set -r safeslinger.msgrxml -l be res/values-be/strings.xml
tx set -r safeslinger.msgrxml -l bn res/values-bn/strings.xml
tx set -r safeslinger.msgrxml -l bs res/values-bs/strings.xml
tx set -r safeslinger.msgrxml -l bg res/values-bg/strings.xml
tx set -r safeslinger.msgrxml -l ca res/values-ca/strings.xml
tx set -r safeslinger.msgrxml -l ceb res/values-cb/strings.xml
tx set -r safeslinger.msgrxml -l zh_CN res/values-zh-rCN/strings.xml
tx set -r safeslinger.msgrxml -l zh_TW res/values-zh-rTW/strings.xml
tx set -r safeslinger.msgrxml -l hr res/values-hr/strings.xml
tx set -r safeslinger.msgrxml -l cs res/values-cs/strings.xml
tx set -r safeslinger.msgrxml -l da res/values-da/strings.xml
tx set -r safeslinger.msgrxml -l nl res/values-nl/strings.xml
tx set --source -r safeslinger.msgrxml -l en res/values/strings.xml
tx set -r safeslinger.msgrxml -l eo res/values-eo/strings.xml
tx set -r safeslinger.msgrxml -l et res/values-et/strings.xml
tx set -r safeslinger.msgrxml -l tl res/values-tl/strings.xml
tx set -r safeslinger.msgrxml -l fi res/values-fi/strings.xml
tx set -r safeslinger.msgrxml -l fr res/values-fr/strings.xml
tx set -r safeslinger.msgrxml -l gl res/values-gl/strings.xml
tx set -r safeslinger.msgrxml -l ka res/values-ka/strings.xml
tx set -r safeslinger.msgrxml -l de res/values-de/strings.xml
tx set -r safeslinger.msgrxml -l el res/values-el/strings.xml
tx set -r safeslinger.msgrxml -l gu res/values-gu/strings.xml
tx set -r safeslinger.msgrxml -l ht res/values-ht/strings.xml
tx set -r safeslinger.msgrxml -l ha res/values-ha/strings.xml
tx set -r safeslinger.msgrxml -l he res/values-iw/strings.xml
tx set -r safeslinger.msgrxml -l hi res/values-hi/strings.xml
tx set -r safeslinger.msgrxml -l hmn res/values-hm/strings.xml
tx set -r safeslinger.msgrxml -l hu res/values-hu/strings.xml
tx set -r safeslinger.msgrxml -l is res/values-is/strings.xml
tx set -r safeslinger.msgrxml -l ig res/values-ig/strings.xml
tx set -r safeslinger.msgrxml -l id res/values-in/strings.xml
tx set -r safeslinger.msgrxml -l ga res/values-ga/strings.xml
tx set -r safeslinger.msgrxml -l it res/values-it/strings.xml
tx set -r safeslinger.msgrxml -l ja res/values-ja/strings.xml
tx set -r safeslinger.msgrxml -l jv res/values-jv/strings.xml
tx set -r safeslinger.msgrxml -l kn res/values-kn/strings.xml
tx set -r safeslinger.msgrxml -l km res/values-km/strings.xml
tx set -r safeslinger.msgrxml -l ko res/values-ko/strings.xml
tx set -r safeslinger.msgrxml -l lo res/values-lo/strings.xml
tx set -r safeslinger.msgrxml -l la res/values-la/strings.xml
tx set -r safeslinger.msgrxml -l lv res/values-lv/strings.xml
tx set -r safeslinger.msgrxml -l lt res/values-lt/strings.xml
tx set -r safeslinger.msgrxml -l mk res/values-mk/strings.xml
tx set -r safeslinger.msgrxml -l ms res/values-ms/strings.xml
tx set -r safeslinger.msgrxml -l mt res/values-mt/strings.xml
tx set -r safeslinger.msgrxml -l mi res/values-mi/strings.xml
tx set -r safeslinger.msgrxml -l mr res/values-mr/strings.xml
tx set -r safeslinger.msgrxml -l mn res/values-mn/strings.xml
tx set -r safeslinger.msgrxml -l ne res/values-ne/strings.xml
tx set -r safeslinger.msgrxml -l no res/values-no/strings.xml
tx set -r safeslinger.msgrxml -l fa res/values-fa/strings.xml
tx set -r safeslinger.msgrxml -l pl res/values-pl/strings.xml
tx set -r safeslinger.msgrxml -l pt res/values-pt/strings.xml
tx set -r safeslinger.msgrxml -l pa res/values-pa/strings.xml
tx set -r safeslinger.msgrxml -l ro res/values-ro/strings.xml
tx set -r safeslinger.msgrxml -l ru res/values-ru/strings.xml
tx set -r safeslinger.msgrxml -l sr res/values-sr/strings.xml
tx set -r safeslinger.msgrxml -l sk res/values-sk/strings.xml
tx set -r safeslinger.msgrxml -l sl res/values-sl/strings.xml
tx set -r safeslinger.msgrxml -l so res/values-so/strings.xml
tx set -r safeslinger.msgrxml -l es res/values-es/strings.xml
tx set -r safeslinger.msgrxml -l sw res/values-sw/strings.xml
tx set -r safeslinger.msgrxml -l sv res/values-sv/strings.xml
tx set -r safeslinger.msgrxml -l ta res/values-ta/strings.xml
tx set -r safeslinger.msgrxml -l te res/values-te/strings.xml
tx set -r safeslinger.msgrxml -l th res/values-th/strings.xml
tx set -r safeslinger.msgrxml -l tr res/values-tr/strings.xml
tx set -r safeslinger.msgrxml -l uk res/values-uk/strings.xml
tx set -r safeslinger.msgrxml -l ur res/values-ur/strings.xml
tx set -r safeslinger.msgrxml -l vi res/values-vi/strings.xml
tx set -r safeslinger.msgrxml -l cy res/values-cy/strings.xml
tx set -r safeslinger.msgrxml -l yi res/values-ji/strings.xml
tx set -r safeslinger.msgrxml -l yo res/values-yo/strings.xml
tx set -r safeslinger.msgrxml -l zu res/values-zu/strings.xml